name: PR Check

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests Locally
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- NEW STEP HERE ---
      - name: Install Dependencies
        run: bundle install

      - name: Real Test Run
        run: bundle exec fastlane pr_check